import { ProductItem } from '@/app/api/shop/route';

export const INITIAL_GEMSTONE_PRODUCTS: ProductItem[] = [
  {
    id: 'gem-pukhraj-ceylon-1',
    sku: 'SKU-GEM-89201',
    title: 'Natural Ceylon Yellow Sapphire (Pukhraj) - 4.25 Carat',
    category: 'Gemstones',
    subCategory: 'Precious Gemstones',
    rulingPlanet: 'Jupiter (Guru / বৃহস্পতি)',
    zodiacRashi: 'Sagittarius (Dhanu), Pisces (Meen)',
    caratWeight: 4.25,
    rattiWeight: 4.67,
    origin: 'Ratnapura, Sri Lanka (Ceylon)',
    color: 'Vivid Golden Canary Yellow',
    cutShape: 'Oval Brilliant Mixed Cut',
    treatment: '100% Natural & Untreated / Unheated',
    certification: 'Govt. Lab Certified (GIA / IGI Standards)',
    recommendedMetal: '22K/18K Yellow Gold or Panchdhatu',
    wearingFinger: 'Index Finger of Right Hand',
    wearingDayTime: 'Thursday Morning (Shukla Paksha) during Guru Hora',
    vedicMantra: 'Om Brim Brihaspataye Namah (ॐ बृं बृहस्पतये नमः)',
    shortDescription: 'Top-grade Ceylon Yellow Sapphire with high luster and eye-clean clarity. Bestows divine wisdom, wealth, spiritual elevation, and matrimonial bliss.',
    description: 'Authentic, unheated, and untreated Ceylon Yellow Sapphire (Pukhraj) sourced directly from the historic mines of Ratnapura, Sri Lanka. Renowned for its radiant canary yellow brilliance, this gemstone channels the pure benevolent vibrations of Lord Brihaspati (Jupiter). It is consecrated by expert Vedic Acharyas with Vedic Beej Mantras prior to shipping, making it ready for auspicious wearing.',
    price: 43700,
    originalPrice: 52000,
    stock: 4,
    rating: 4.9,
    reviewsCount: 48,
    badge: 'BESTSELLER • 100% UNHEATED',
    image: '/assets/products/pukhraj_p1.png',
    images: [
      '/assets/products/pukhraj_p1.png',
      '/assets/products/pukhraj_p2.png'
    ],
    features: [
      '100% Natural & Untreated Ceylon Yellow Sapphire',
      'Govt. Recognized Gemological Laboratory Certificate Included',
      'Individually Energized with Brihaspati Vedic Mantras',
      'Free Insured Express Delivery across India'
    ],
    isFeatured: true,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-neelam-ceylon-2',
    sku: 'SKU-GEM-89202',
    title: 'Natural Royal Blue Sapphire (Neelam) - 3.80 Carat',
    category: 'Gemstones',
    subCategory: 'Precious Gemstones',
    rulingPlanet: 'Saturn (Shani / শনি)',
    zodiacRashi: 'Capricorn (Makar), Aquarius (Kumbh)',
    caratWeight: 3.8,
    rattiWeight: 4.18,
    origin: 'Sri Lanka (Ceylon)',
    color: 'Royal Cornflower Deep Blue',
    cutShape: 'Cushion Brilliant Cut',
    treatment: '100% Natural & Unheated',
    certification: 'IGI / IGL Certified Lab Tested',
    recommendedMetal: 'Silver, White Gold or Ashtadhatu',
    wearingFinger: 'Middle Finger of Right Hand',
    wearingDayTime: 'Saturday Evening (Shani Hora)',
    vedicMantra: 'Om Sham Shanaicharaya Namah (ॐ शं शनैश्चराय नमः)',
    shortDescription: 'High-transparency unheated Ceylon Blue Sapphire with rich royal blue saturation. Accelerates career breakthroughs, discipline, and sudden fortunes.',
    description: 'Exquisite Natural Ceylon Blue Sapphire (Neelam) exhibiting exceptional velvety royal blue saturation without heat treatment. As the gemstone of Lord Shani (Saturn), Blue Sapphire is the fastest-acting stone in Vedic astrology, clearing professional blockages, shielding from malefic gaze (evil eye), and unlocking massive career milestones.',
    price: 55200,
    originalPrice: 65000,
    stock: 3,
    rating: 5.0,
    reviewsCount: 64,
    badge: 'ROYAL GRADE • FAST ACTING',
    image: '/assets/products/neelam_single_1789189245796.jpg',
    images: [
      '/assets/products/neelam_single_1789189245796.jpg',
      '/assets/products/neelam_multiview_1789189284857.jpg'
    ],
    features: [
      'Unheated & Untreated Ceylon Gemstone',
      'Lab Authenticated with QR Verifiable Certificate',
      'Vedic Shani Shanti Pooja & Consecration Completed',
      '10-Day Vedic Trial Satisfaction Guarantee'
    ],
    isFeatured: true,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-panna-zambian-3',
    sku: 'SKU-GEM-89203',
    title: 'Natural Zambian Emerald (Panna) - 5.15 Carat',
    category: 'Gemstones',
    subCategory: 'Precious Gemstones',
    rulingPlanet: 'Mercury (Budha / বুধ)',
    zodiacRashi: 'Gemini (Mithun), Virgo (Kanya)',
    caratWeight: 5.15,
    rattiWeight: 5.66,
    origin: 'Kagem Mines, Zambia',
    color: 'Vivid Deep Forest Green',
    cutShape: 'Emerald Octagon Step Cut',
    treatment: 'Minor Colorless Oil (Traditional Standard)',
    certification: 'Govt. Lab Certified (GTL / IGI)',
    recommendedMetal: 'Gold, Panchdhatu or Silver',
    wearingFinger: 'Little Finger (Kanishtha) of Right Hand',
    wearingDayTime: 'Wednesday Morning during Budha Hora',
    vedicMantra: 'Om Bum Budhaya Namah (ॐ बुं बुधाय नमः)',
    shortDescription: 'Lustrous Zambian Emerald boasting vivid green hues and excellent crystal transparency. Enhances communication, business intellect, and memory power.',
    description: 'Selected from the renowned Kagem emerald mines of Zambia, this natural Emerald (Panna) features a balanced octagonal step cut with mesmerizing forest green transparency. Governed by Budha (Mercury), wearing this gemstone boosts eloquence, academic success, financial acumen, and sharp computational intellect.',
    price: 36800,
    originalPrice: 44000,
    stock: 5,
    rating: 4.8,
    reviewsCount: 39,
    badge: 'VIVID GREEN • INTELLECT',
    image: '/assets/products/panna_single_1789189322603.jpg',
    images: [
      '/assets/products/panna_single_1789189322603.jpg',
      '/assets/products/panna_multiview_1789189376159.jpg'
    ],
    features: [
      'Deep Vivid Green Zambian Origin',
      'Lab Certified for Clarity & Authenticity',
      'Consecrated with Budha Vedic Mantras',
      'Free Custom Ring / Pendant Mounting Guidance'
    ],
    isFeatured: true,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-manik-burmese-4',
    sku: 'SKU-GEM-89204',
    title: 'Natural Old-Mine Burmese Ruby (Manik) - 3.45 Carat',
    category: 'Gemstones',
    subCategory: 'Precious Gemstones',
    rulingPlanet: 'Sun (Surya / সূর্য)',
    zodiacRashi: 'Leo (Simha)',
    caratWeight: 3.45,
    rattiWeight: 3.79,
    origin: 'Mogok Valley, Myanmar (Burma)',
    color: 'Pigeon Blood Red',
    cutShape: 'Oval Faceted Mixed Cut',
    treatment: '100% Natural & Unheated',
    certification: 'GIA / IGI Standards Lab Certificate',
    recommendedMetal: '22K/18K Yellow Gold or Copper',
    wearingFinger: 'Ring Finger (Anamika) of Right Hand',
    wearingDayTime: 'Sunday Morning at Sunrise (Surya Hora)',
    vedicMantra: 'Om Hrim Sum Suryaya Namah (ॐ ह्रीं सूं सूर्याय नमः)',
    shortDescription: 'Rare Pigeon Blood Burmese Ruby with fiery red scintillation. Bestows leadership authority, government administrative success, and robust heart vitality.',
    description: 'Authentic, unheated Natural Ruby (Manikya) hailing from the fabled Mogok mines of Myanmar. Revered as the \'King of Gemstones\', this ruby displays the prized Pigeon Blood red shade that channels the supreme leadership, confidence, and vital solar energy of Lord Surya Dev.',
    price: 63250,
    originalPrice: 75000,
    stock: 2,
    rating: 4.9,
    reviewsCount: 53,
    badge: 'PIGEON BLOOD • RARE ROYAL',
    image: '/assets/products/manik_single_1789189417773.jpg',
    images: [
      '/assets/products/manik_single_1789189417773.jpg',
      '/assets/products/manik_multiview_1789189470757.jpg'
    ],
    features: [
      'Historic Mogok Burma Origin Unheated Ruby',
      'Government Lab Certification with High Security QR',
      'Surya Gayatri Consecrated by Vedic Pandits',
      'Includes Certificate & Premium Wooden Gem Box'
    ],
    isFeatured: true,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-moonga-italian-5',
    sku: 'SKU-GEM-89205',
    title: 'Natural Red Coral (Italian Moonga) Capsule - 7.20 Ratti',
    category: 'Gemstones',
    subCategory: 'Vedic Astrological Gems',
    rulingPlanet: 'Mars (Mangal / মঙ্গল)',
    zodiacRashi: 'Aries (Mesh), Scorpio (Vrishchik)',
    caratWeight: 6.55,
    rattiWeight: 7.2,
    origin: 'Mediterranean Sea, Italy',
    color: 'Ox-Blood Deep Crimson Red',
    cutShape: 'Capsule / Cylindrical Cabochon',
    treatment: '100% Natural Organic & Untreated',
    certification: 'Govt. Lab Certified Natural Coral',
    recommendedMetal: 'Copper, Gold or Panchdhatu',
    wearingFinger: 'Ring Finger of Right Hand',
    wearingDayTime: 'Tuesday Morning (Mangal Hora)',
    vedicMantra: 'Om Kram Krim Kraum Sah Bhaumaya Namah (ॐ क्रां क्रीं क्रौं सः भौमाय नमः)',
    shortDescription: 'Pristine Italian Red Coral with smooth lustrous porcelain surface. Cures Manglik Dosh, elevates physical stamina, and grants victory over debts and rivals.',
    description: 'High-grade Mediterranean Italian Red Coral (Moonga) crafted into the auspicious cylindrical capsule cabochon. Representing Mangal (Mars), the celestial commander, this energized coral destroys lethargy, balances blood vitality, cures Manglik obstacles in marriage, and accelerates real estate/property acquisitions.',
    price: 14950,
    originalPrice: 18000,
    stock: 8,
    rating: 4.8,
    reviewsCount: 42,
    badge: 'OX-BLOOD • MANGLIK CURE',
    image: '/assets/products/moonga_single_1789189542547.jpg',
    images: [
      '/assets/products/moonga_single_1789189542547.jpg',
      '/assets/products/moonga_multiview_1789189592700.jpg'
    ],
    features: [
      'Natural Mediterranean Italian Coral',
      'Pores-Free Smooth Porcelain Finish',
      'Mangal Gayatri Energization Rituals Performed',
      'Direct Laboratory Testing Certificate'
    ],
    isFeatured: false,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-moti-basra-6',
    sku: 'SKU-GEM-89206',
    title: 'Natural South Sea Pearl (Moti) - 8.50 Ratti',
    category: 'Gemstones',
    subCategory: 'Vedic Astrological Gems',
    rulingPlanet: 'Moon (Chandra / চন্দ্র)',
    zodiacRashi: 'Cancer (Kark)',
    caratWeight: 7.73,
    rattiWeight: 8.5,
    origin: 'South Sea, Australia',
    color: 'Silvery White with Pinkish Luster',
    cutShape: 'Near Round Button Cabochon',
    treatment: '100% Natural Cultured Organic',
    certification: 'Govt. Lab Certified Pearl',
    recommendedMetal: 'Pure Silver (Chandi)',
    wearingFinger: 'Little Finger of Right Hand',
    wearingDayTime: 'Monday Morning (Chandra Hora) or Full Moon Evening',
    vedicMantra: 'Om Shram Shrim Shraum Sah Chandraya Namah (ॐ श्रां श्रीं श्रौं सः चन्द्राय नमः)',
    shortDescription: 'Luminous South Sea Pearl radiating cool maternal tranquility. Balances emotional turbulence, calms depression, and bestows peaceful restful sleep.',
    description: 'Flawlessly lustrous South Sea Pearl (Moti) known for its thick nacre and soothing silvery-white orient. Governed by Chandra (Moon), this consecrated pearl stabilizes erratic emotions, overcomes chronic anxiety and insomnia, and fosters unconditional familial harmony.',
    price: 18400,
    originalPrice: 22000,
    stock: 6,
    rating: 4.9,
    reviewsCount: 35,
    badge: 'LUMINOUS • EMOTIONAL CALM',
    image: '/assets/products/moti_single_1789189638802.jpg',
    images: [
      '/assets/products/moti_single_1789189638802.jpg',
      '/assets/products/moti_multiview_1789189699723.jpg'
    ],
    features: [
      'Thick Nacre Natural South Sea Pearl',
      'Silver-Pink High Mirror Luster',
      'Chandra Mantra Consecration with Gangajal',
      'Certified by Registered Gemological Laboratory'
    ],
    isFeatured: false,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-gomed-ceylon-7',
    sku: 'SKU-GEM-89207',
    title: 'Natural Ceylon Hessonite Garnet (Gomed) - 6.10 Carat',
    category: 'Gemstones',
    subCategory: 'Vedic Astrological Gems',
    rulingPlanet: 'Rahu (North Node / রাহু)',
    zodiacRashi: 'Suitable for Rahu Mahadasha / Aquarius / Taurus',
    caratWeight: 6.1,
    rattiWeight: 6.71,
    origin: 'Sri Lanka (Ceylon)',
    color: 'Deep Honey Cinnamon Brown',
    cutShape: 'Oval Cushion Mixed Cut',
    treatment: '100% Natural & Untreated',
    certification: 'IGI / Govt. Lab Certified',
    recommendedMetal: 'Silver or Ashtadhatu',
    wearingFinger: 'Middle Finger of Right Hand',
    wearingDayTime: 'Saturday Night / Sunset during Rahu Kaal transition',
    vedicMantra: 'Om Bhram Bhrim Bhraum Sah Rahave Namah (ॐ भ्रां भ्रीं भ्रौं सः राहवे नमः)',
    shortDescription: 'Authentic Ceylon Hessonite (Gomed) with rich honey-whiskey hue. Pacifies Rahu Mahadasha, protects against sudden legal traps, and accelerates tech innovation.',
    description: 'Natural Ceylon Hessonite Garnet (Gomed) featuring the classic transparent \'cow urine\' honey-cinnamon color celebrated in ancient Brihat Samhita. As the gemstone of shadow planet Rahu, it dissolves mysterious fears, legal litigations, gambling addiction, and grants rapid speculative and digital commerce success.',
    price: 16100,
    originalPrice: 19500,
    stock: 5,
    rating: 4.7,
    reviewsCount: 29,
    badge: 'HONEY CEYLON • RAHU SHANTI',
    image: '/assets/products/gomed_single_1789189755177.jpg',
    images: [
      '/assets/products/gomed_single_1789189755177.jpg'
    ],
    features: [
      'Natural Untreated Ceylon Hessonite',
      'Deep Honey Amber Transparency',
      'Consecrated with Rahu Beej Mantras',
      'Tamper-Evident Lab Sealed Packaging'
    ],
    isFeatured: false,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-catseye-ceylon-8',
    sku: 'SKU-GEM-89208',
    title: 'Natural Chrysoberyl Cat\'s Eye (Lehsunia) - 4.50 Carat',
    category: 'Gemstones',
    subCategory: 'Vedic Astrological Gems',
    rulingPlanet: 'Ketu (South Node / কেতু)',
    zodiacRashi: 'Suitable for Ketu Dasha / Pisces / Sagittarius',
    caratWeight: 4.5,
    rattiWeight: 4.95,
    origin: 'Sri Lanka (Ceylon)',
    color: 'Greenish Golden Honey with Sharp White Ray',
    cutShape: 'Oval High-Dome Cabochon',
    treatment: '100% Natural & Untreated',
    certification: 'Govt. Lab Certified Chrysoberyl',
    recommendedMetal: 'Silver or Panchdhatu',
    wearingFinger: 'Middle Finger or Little Finger',
    wearingDayTime: 'Tuesday or Thursday Midnight',
    vedicMantra: 'Om Stram Strim Straum Sah Ketave Namah (ॐ स्रां स्रीं स्रौं सः केतवे नमः)',
    shortDescription: 'Top-grade Chrysoberyl Cat\'s Eye with intense sharp chatoyant band. Enhances psychic intuition, guards against spiritual attacks, and cleanses karmic debts.',
    description: 'Rare Natural Chrysoberyl Cat\'s Eye (Lehsunia / Vaiduryam) with a razor-sharp, centralized moving chatoyancy line (the \'milk and honey\' effect). Governed by Ketu, this mystical gemstone grants spiritual moksha, protects from accidental perils, and resurrects collapsed businesses.',
    price: 28750,
    originalPrice: 34000,
    stock: 3,
    rating: 4.9,
    reviewsCount: 27,
    badge: 'SHARP CHATOYANCY • KETU',
    image: '/assets/products/gem_catseye_single.jpg',
    images: [
      '/assets/products/gem_catseye_single.jpg',
      '/assets/products/gem_catseye_multi.jpg'
    ],
    features: [
      'Natural Chrysoberyl (Not Quartz)',
      'High-Dome Sharp Chatoyant Ray',
      'Ketu Consecration Rituals Conducted',
      'Govt. Recognized Lab Certification'
    ],
    isFeatured: false,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-opal-australian-9',
    sku: 'SKU-GEM-89209',
    title: 'Natural Australian Fire Opal - 5.80 Carat',
    category: 'Gemstones',
    subCategory: 'Vedic Astrological Gems',
    rulingPlanet: 'Venus (Shukra / শুক্র)',
    zodiacRashi: 'Taurus (Vrishabh), Libra (Tula)',
    caratWeight: 5.8,
    rattiWeight: 6.38,
    origin: 'Coober Pedy, Australia',
    color: 'Milky White with Vivid Multi-Color Play of Fire',
    cutShape: 'Oval Smooth Cabochon',
    treatment: '100% Natural Solid Opal',
    certification: 'Govt. Lab Certified Natural Opal',
    recommendedMetal: 'Silver, Platinum or White Gold',
    wearingFinger: 'Ring Finger or Index Finger',
    wearingDayTime: 'Friday Morning during Shukra Hora',
    vedicMantra: 'Om Shum Shukraya Namah (ॐ शुं शुक्राय नमः)',
    shortDescription: 'Dazzling Australian White Opal featuring rich multi-colored prismatic flash. Enhances marital luxury, artistic creativity, romance, and Venusian prosperity.',
    description: 'Premium Natural Australian Solid Opal bursting with rainbow holographic fire (play-of-color). Regarded as the primary Vedic gemstone surrogate for Diamond, Opal radiates Shukra\'s divine glamour, luxury lifestyle, romantic attraction, and artistic excellence.',
    price: 20700,
    originalPrice: 25000,
    stock: 4,
    rating: 4.9,
    reviewsCount: 44,
    badge: 'RAINBOW FIRE • SHUKRA',
    image: '/assets/products/gem_opal_single.jpg',
    images: [
      '/assets/products/gem_opal_single.jpg',
      '/assets/products/gem_opal_multi.jpg'
    ],
    features: [
      '100% Solid Natural Australian Opal',
      'Vivid Multi-Color Spectral Flash',
      'Shukra Lakshmi Consecration Pooja',
      'Complete Gemological Testing Certificate'
    ],
    isFeatured: false,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-white-sapphire-ceylon-10',
    sku: 'SKU-GEM-89210',
    title: 'Natural Ceylon White Sapphire (Safed Pukhraj) - 4.10 Carat',
    category: 'Gemstones',
    subCategory: 'Precious Gemstones',
    rulingPlanet: 'Venus (Shukra / শুক্র)',
    zodiacRashi: 'Taurus (Vrishabh), Libra (Tula)',
    caratWeight: 4.1,
    rattiWeight: 4.51,
    origin: 'Sri Lanka (Ceylon)',
    color: 'Colorless Diamond White (D-E Grade)',
    cutShape: 'Round Brilliant Cut',
    treatment: '100% Natural & Unheated',
    certification: 'IGI / GIA Standards Lab Certificate',
    recommendedMetal: 'White Gold, Platinum or Silver',
    wearingFinger: 'Ring Finger or Middle Finger',
    wearingDayTime: 'Friday Morning (Shukra Hora)',
    vedicMantra: 'Om Draam Dreem Draum Sah Shukraya Namah (ॐ द्रां द्रीं द्रौं सः शुक्राय नमः)',
    shortDescription: 'Untreated Ceylon White Sapphire with diamond-like fire and hardness (Mohs 9). Bestows high luxury, marital romance, and magnetic charismatic appeal.',
    description: 'Natural Ceylon White Sapphire (Safed Pukhraj) possessing diamond-equivalent optical brilliance and exceptional 9 Mohs durability. It acts as the premier astrological diamond substitute to invoke the divine blessings of Goddess Mahalakshmi and Lord Shukra without diamond\'s astronomical cost.',
    price: 32200,
    originalPrice: 38000,
    stock: 3,
    rating: 4.8,
    reviewsCount: 31,
    badge: 'DIAMOND ALTERNATIVE • UNHEATED',
    image: '/assets/products/gem_white_sapphire_single.jpg',
    images: [
      '/assets/products/gem_white_sapphire_single.jpg',
      '/assets/products/gem_white_sapphire_multi.jpg'
    ],
    features: [
      '100% Natural Unheated Ceylon White Sapphire',
      'Diamond Equivalent Luster & Fire',
      'Consecrated with Shukra Beej Mantras',
      'Full Laboratory Certification Included'
    ],
    isFeatured: false,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-pitambari-ceylon-11',
    sku: 'SKU-GEM-89211',
    title: 'Natural Ceylon Pitambari Neelambari Sapphire - 3.90 Carat',
    category: 'Gemstones',
    subCategory: 'Precious Gemstones',
    rulingPlanet: 'Jupiter & Saturn Dual Synergy (Guru-Shani / বৃহস্পতি-শনি)',
    zodiacRashi: 'Dhanu, Makar, Kumbh, Meen',
    caratWeight: 3.9,
    rattiWeight: 4.29,
    origin: 'Sri Lanka (Ceylon)',
    color: 'Bi-Color Dual Yellow & Royal Blue',
    cutShape: 'Cushion Brilliant Cut',
    treatment: '100% Natural & Untreated',
    certification: 'Govt. Lab Certified Bi-Color Corundum',
    recommendedMetal: 'Gold & Silver Two-Tone or Panchdhatu',
    wearingFinger: 'Middle Finger or Index Finger',
    wearingDayTime: 'Thursday or Saturday Morning',
    vedicMantra: 'Om Brihaspataye Shanaishcharaya Namah (ॐ बृहस्पतये शनैश्चराय नमः)',
    shortDescription: 'Rare bi-color Pitambari Sapphire uniting Jupiter\'s wisdom with Saturn\'s discipline. Bestows executive mastery, massive wealth, and karmic protection.',
    description: 'A collector-grade Natural Ceylon Pitambari Sapphire displaying distinct dual zones of golden yellow and celestial royal blue in a single corundum crystal. This rare cosmic combination harmonizes the expansive blessings of Guru (Jupiter) with the karmic grounding of Shani (Saturn).',
    price: 57500,
    originalPrice: 68000,
    stock: 2,
    rating: 5.0,
    reviewsCount: 26,
    badge: 'RARE BI-COLOR • GURU-SHANI',
    image: '/assets/products/gem_pitambari_single.jpg',
    images: [
      '/assets/products/gem_pitambari_single.jpg',
      '/assets/products/gem_pitambari_multi.jpg'
    ],
    features: [
      'Rare Natural Untreated Pitambari Corundum',
      'Distinct Golden Yellow & Blue Color Zoning',
      'Dual Guru & Shani Consecration Pooja',
      'Certified by Leading Gemological Institute'
    ],
    isFeatured: true,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-amethyst-brazil-12',
    sku: 'SKU-GEM-89212',
    title: 'Natural Deep Purple Amethyst (Katela / Jamunia) - 7.50 Carat',
    category: 'Gemstones',
    subCategory: 'Vedic Astrological Gems',
    rulingPlanet: 'Saturn Upratna (Shani Sub-stone / শনি উপ-রত্ন)',
    zodiacRashi: 'Capricorn (Makar), Aquarius (Kumbh)',
    caratWeight: 7.5,
    rattiWeight: 8.25,
    origin: 'Rio Grande do Sul, Brazil',
    color: 'Deep Royal Siberian Purple',
    cutShape: 'Emerald Cut Faceted',
    treatment: '100% Natural & Untreated',
    certification: 'Govt. Lab Certified Natural Amethyst',
    recommendedMetal: 'Silver or White Metal',
    wearingFinger: 'Middle Finger of Right Hand',
    wearingDayTime: 'Saturday Evening during Shani Hora',
    vedicMantra: 'Om Sham Shanaicharaya Namah (ॐ शं शनैश्चराय नमः)',
    shortDescription: 'Deep royal purple Brazilian Amethyst (Jamunia). The most potent affordable substitute for Blue Sapphire, detoxifying the mind and eliminating Saturn distress.',
    description: 'Natural Brazilian Amethyst (Katela/Jamunia) exhibiting the prized deep Siberian purple saturation with zero brownish undertones. Renowned in Vedic gemology as the primary Upratna (sub-stone) for Blue Sapphire, Amethyst cures chronic stress, insomnia, addictions, and relieves Sade Sati hardships.',
    price: 9200,
    originalPrice: 11500,
    stock: 10,
    rating: 4.8,
    reviewsCount: 58,
    badge: 'SHANI UPRATNA • STRESS CURE',
    image: '/assets/products/gem_amethyst_single.jpg',
    images: [
      '/assets/products/gem_amethyst_single.jpg',
      '/assets/products/gem_amethyst_multi.jpg'
    ],
    features: [
      'Vivid Royal Purple Brazilian Amethyst',
      'Budget-Friendly Alternative to Blue Sapphire',
      'Shani Shanti Mantras Energized',
      'Laboratory Authenticated Quality'
    ],
    isFeatured: false,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-peridot-pakistan-13',
    sku: 'SKU-GEM-89213',
    title: 'Natural Pakistani Peridot (Zabargad) - 6.20 Carat',
    category: 'Gemstones',
    subCategory: 'Vedic Astrological Gems',
    rulingPlanet: 'Mercury Upratna (Budha Sub-stone / বুধ উপ-রত্ন)',
    zodiacRashi: 'Gemini (Mithun), Virgo (Kanya)',
    caratWeight: 6.2,
    rattiWeight: 6.82,
    origin: 'Suppatt Mines, Kohistan, Pakistan',
    color: 'Vibrant Olive Apple Green',
    cutShape: 'Cushion Brilliant Cut',
    treatment: '100% Natural & Untreated',
    certification: 'Govt. Lab Certified Peridot',
    recommendedMetal: 'Silver, White Gold or Panchdhatu',
    wearingFinger: 'Little Finger of Right Hand',
    wearingDayTime: 'Wednesday Morning (Budha Hora)',
    vedicMantra: 'Om Bum Budhaya Namah (ॐ बुं बुधाय नमः)',
    shortDescription: 'Sparkling Apple-Green Pakistani Peridot. Highly effective affordable alternative to Emerald, enhancing academic focus, clear speech, and nervous system health.',
    description: 'Luminous Natural Pakistani Peridot (Zabargad) displaying exceptional crystal transparency and vivid olive green glow. As the chief Upratna for Panna (Emerald), Peridot removes nervous stammering, boosts analytical computing skills, and dissolves mental gloom.',
    price: 10350,
    originalPrice: 12500,
    stock: 7,
    rating: 4.7,
    reviewsCount: 36,
    badge: 'PANNA UPRATNA • INTELLECT',
    image: '/assets/products/gem_peridot_single.jpg',
    images: [
      '/assets/products/gem_peridot_single.jpg',
      '/assets/products/gem_peridot_multi.jpg'
    ],
    features: [
      '100% Natural Untreated Himalayan Peridot',
      'Clean Emerald Alternative with High Luster',
      'Budha Mantra Energized with Green Tulsi',
      'Official Lab Certificate Included'
    ],
    isFeatured: false,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-citrine-brazil-14',
    sku: 'SKU-GEM-89214',
    title: 'Natural Golden Madeira Citrine (Sunela) - 8.10 Carat',
    category: 'Gemstones',
    subCategory: 'Vedic Astrological Gems',
    rulingPlanet: 'Jupiter Upratna (Guru Sub-stone / বৃহস্পতি উপ-রত্ন)',
    zodiacRashi: 'Sagittarius (Dhanu), Pisces (Meen)',
    caratWeight: 8.1,
    rattiWeight: 8.91,
    origin: 'Minas Gerais, Brazil',
    color: 'Golden Madeira Whiskey Amber',
    cutShape: 'Oval Brilliant Cut',
    treatment: '100% Natural & Untreated',
    certification: 'Govt. Lab Certified Natural Citrine',
    recommendedMetal: 'Gold or Brass / Panchdhatu',
    wearingFinger: 'Index Finger of Right Hand',
    wearingDayTime: 'Thursday Morning (Guru Hora)',
    vedicMantra: 'Om Gram Grim Graum Sah Gurave Namah (ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः)',
    shortDescription: 'Golden Madeira Citrine (Sunela) known as the \'Merchant\'s Wealth Stone\'. Most popular affordable Pukhraj substitute for continuous cash flow and career growth.',
    description: 'Natural Golden Citrine (Sunela) glowing with warm madeira amber brilliance. Known worldwide as the \'Success Stone\' and the primary Vedic sub-stone for Yellow Sapphire, Citrine activates the Solar Plexus chakra, attracts business profits, and promotes generous wealth multiplication.',
    price: 8625,
    originalPrice: 10500,
    stock: 12,
    rating: 4.9,
    reviewsCount: 61,
    badge: 'MERCHANT WEALTH STONE • GURU',
    image: '/assets/products/gem_citrine_single.jpg',
    images: [
      '/assets/products/gem_citrine_single.jpg',
      '/assets/products/gem_citrine_multi.jpg'
    ],
    features: [
      'Natural Brazilian Golden Citrine',
      'Most Popular Pukhraj Substitute',
      'Consecrated with Brihaspati & Lakshmi Mantras',
      'Includes Lab Testing Guarantee'
    ],
    isFeatured: false,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-rudraksha-5mukhi-15',
    sku: 'SKU-MAL-89215',
    title: 'Collector Grade Consecrated 5 Mukhi Nepal Rudraksha Mala (108+1 Beads)',
    category: 'Yantras & Mala',
    subCategory: 'Sacred Beads & Malas',
    rulingPlanet: 'Jupiter (Guru) / Lord Shiva',
    zodiacRashi: 'All Rashis (Universal Auspiciousness)',
    caratWeight: 0,
    rattiWeight: 0,
    origin: 'Pashupatinath Sacred Valley, Nepal',
    color: 'Natural Lustrous Brown',
    cutShape: 'Spherical Natural Fluted Beads (8mm)',
    treatment: '100% Authentic Natural Organic',
    certification: 'Certified Lab Tested Rudraksha',
    recommendedMetal: 'Pure Silk Thread with Silver Caps',
    wearingFinger: 'Neck Mala / Japa Meditation',
    wearingDayTime: 'Monday Morning or Maha Shivratri',
    vedicMantra: 'Om Hrim Namah / Om Namah Shivaya (ॐ नमः शिवाय)',
    shortDescription: '108+1 Premium Nepali 5 Mukhi Rudraksha beads strung in pure thread. Consecrated with Shiva Abhishekam for supreme peace, blood pressure regulation, and spiritual aura.',
    description: 'Hand-picked Collector-Grade 5 Mukhi Nepali Rudraksha Mala (108+1 beads) sourced directly from high-altitude groves of Nepal. Consecrated with Rudrabhishek rituals, this sacred rosary shields the wearer from negative psychic energies, lowers hypertension, and aids deep meditation.',
    price: 3450,
    originalPrice: 4200,
    stock: 15,
    rating: 5.0,
    reviewsCount: 82,
    badge: '100% NEPALI • SHIVA BLESSED',
    image: '/assets/products/rudraksha_single.jpg',
    images: [
      '/assets/products/rudraksha_single.jpg',
      '/assets/products/rudraksha_multi.jpg'
    ],
    features: [
      '100% Genuine High-Altitude Nepal Rudraksha',
      'Smooth 8mm Beads with 108+1 Sumeru Bead',
      'Blessed with Holy Ganga & Pashupatinath Rituals',
      'Authenticity Certificate Included'
    ],
    isFeatured: true,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  },
  {
    id: 'gem-shree-yantra-24k-16',
    sku: 'SKU-YAN-89216',
    title: '24K Gold Plated Maha Meru Shree Yantra (Heavy Brass Core)',
    category: 'Yantras & Mala',
    subCategory: 'Consecrated Sacred Yantras',
    rulingPlanet: 'Goddess Mahalakshmi & Venus',
    zodiacRashi: 'All Rashis (Universal Vastu Blessing)',
    caratWeight: 0,
    rattiWeight: 0,
    origin: 'Varanasi Vedic Artisan Guild',
    color: '24K Mirror Gold Polish',
    cutShape: '3D Pyramid Maha Meru Geometry (4x4 inches)',
    treatment: '24K Thick Gold Micron Plating over Heavy Brass',
    certification: 'Consecrated & Verified Sacred Geometry',
    recommendedMetal: 'Brass with 24K Gold Plating',
    wearingFinger: 'Temple / Cash Locker / North-East Ishanya Corner',
    wearingDayTime: 'Friday Morning during Shukla Paksha',
    vedicMantra: 'Om Shrim Hrim Shrim Kamale Kamalalaye Prasid Prasid (ॐ श्रीं ह्रीं श्रीं कमले कमलालये प्रसीद प्रसीद)',
    shortDescription: '3D Maha Meru Shree Yantra crafted according to sacred Agamic geometry. Attracts perpetual wealth, destroys Vastu doshas, and energizes home/office aura.',
    description: 'Authentic three-dimensional Maha Meru Shree Yantra engineered with millimetric sacred precision according to ancient Tantric texts. Consecrated with 1008 Sri Sukta chantings, placing this golden Meru in your prayer room, cashier safe, or North-East Ishanya corner attracts unbounded prosperity and eliminates negative Vastu blockages.',
    price: 4370,
    originalPrice: 5200,
    stock: 10,
    rating: 5.0,
    reviewsCount: 94,
    badge: '24K GOLD • MAHALAKSHMI GRACE',
    image: '/assets/products/shree_yantra_single.jpg',
    images: [
      '/assets/products/shree_yantra_single.jpg',
      '/assets/products/shree_yantra_multi.jpg'
    ],
    features: [
      'Flawless 3D Sacred Geometry according to Agamas',
      'Heavy Core with 24K Micron Gold Plating',
      'Energized with 1,008 Sri Sukta Vedic Recitations',
      'Perfect for Home Vastu & Business Cash Counters'
    ],
    isFeatured: true,
    status: 'APPROVED',
    sellerType: 'PLATFORM',
    sellerName: 'KangleiAstro Gemstone Treasury'
  }
];
