plugins {
    id 'com.android.application'
}

android {
    namespace 'in.kuthiyengpham.suryasiddha'
    compileSdk 34

    defaultConfig {
        applicationId "in.kuthiyengpham.suryasiddha"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        manifestPlaceholders = [
            hostName: "kuthiyengpham.in",
            defaultUrl: "https://kuthiyengpham.in/suryasiddha/",
            launcherName: "SuryaSiddha"
        ]
    }

    signingConfigs {
        release {
            storeFile file("android.keystore")
            storePassword "android123"
            keyAlias "android"
            keyPassword "android123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
